apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-webinar
spec:
  type: image
  params:
    - name: url
      value: index.docker.io/jayanthiramalingam/demowebinar    # Replace with your docker hub repo url